name: CapstoneProject
version: '1.0.0'
main: org.jababer.capstoneProject.CapstoneProject
api-version: '1.21'
libraries:
  - com.h2database:h2:2.4.240
commands:
  #Didn't fix before publish.
  database:
    description: "Database command for viewing death logs"
    aliases: [ db, database ]
    usage: "/database <view> [player]"
    permission: capstoneproject.command.db
permissions:
  capstoneproject.command.database:
    #Do true for all users
    default: op

