package org.jababer.capstoneProject.model;

import org.bukkit.Bukkit;
import org.bukkit.damage.DamageSource;
import org.bukkit.entity.Entity;
import org.bukkit.entity.Player;
import org.jababer.capstoneProject.settings.CapstoneProjectSettings;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

/**
 * Database class with full functionality needed for communication
 * 
 * Handles loading, connections, table initialization, closing, and saving 
 */
public final class Database {
    private static final Database instance = new Database();
    private final CapstoneProjectSettings settings;
    private Connection connection;

    private Database() {
        this.settings = CapstoneProjectSettings.getInstance();
    }

    /**
     * Runs needed functions on server start.
     */
    public void load() {
        this.connect();
        this.createTables();
    }

    /**
     * Attempts a conneciton to the database.
     * 
     * Set as H2. Functionality with other databases could be added later, 
     * but fell out of scope for now.
     */
    private void connect() {
        try {
            if (this.connection != null && !this.connection.isClosed()) {
                return;
            }
            if (this.settings.getDatabaseType() == DatabaseType.H2) {
                Class.forName("org.h2.Driver");

                final String jdbcUrl = "jdbc:h2:tcp://" + this.settings.getH2Host() + ":" + this.settings.getH2Port() + "/~/" + this.settings.getH2Database() + ";AUTO_SERVER=TRUE;AUTO_RECONNECT=TRUE";

                Bukkit.getLogger().info("[CapstoneProject] Connecting to database: " + jdbcUrl + " with user " + this.settings.getH2Username());

                this.connection = DriverManager.getConnection(jdbcUrl, this.settings.getH2Username(), this.settings.getH2Password());

                Bukkit.getLogger().info("[CapstoneProject] Successfully connected to database");

            } else {
                Bukkit.getLogger().info("[CapstoneProject] Other databases not implemented yet.");
            }
        } catch (final Exception e) {
            Bukkit.getLogger().info("[CapstoneProject] Failed to connect to database: " + e.getMessage());

            //e.printStackTrace(); Uncomment if needed for testing
        }
    }

    /**
     * Makes sure that the table is created that it is going to put data in.
     * 
     * Creates tables with columns if the table doesn't exist. Additionally,
     * if the connection wasn't established, it tries to connect again.
     */
    private void createTables() {
        try {
            final Statement statement;
            if (this.connection == null) {
                throw new NullPointerException("Connection not created");
            }

            statement = this.connection.createStatement();
            statement.execute("CREATE TABLE IF NOT EXISTS death_log (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "killer_name TEXT NOT NULL, " +
                    "victim_uuid VARCHAR(36) NOT NULL, " +
                    "victim_name TEXT NOT NULL, " +
                    "message TEXT NOT NULL, " +
                    "victim_new_lives INT NOT NULL, " +
                    "timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP," +
                    "description VARCHAR(1000)" +
                    ")");

            statement.execute("CREATE INDEX IF NOT EXISTS idx_death_log_killer_name ON death_log (killer_name)");
            statement.close();
        } catch (final SQLException | NullPointerException e) {
            Bukkit.getLogger().severe("[CapstoneProject] Failed to create tables: " + e.getMessage());

            if (e instanceof NullPointerException) {
                Bukkit.getLogger().severe("[CapstoneProject] Retrying connection to database in 5 seconds...");
                ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor();
                executor.schedule(this::load, 10, TimeUnit.SECONDS);
                executor.shutdown();
            }

        }
    }

    /**
     * Closes the connection with the database
     */
    public void close() {

        try {
            if (this.connection != null && !this.connection.isClosed()) {
                this.connection.close();

                Bukkit.getLogger().info("[CapstoneProject] Successfully closed connection to database");
            }
        } catch (final SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * Sends the death info to the database.
     * 
     * Sends the killer, victim, victim uuid, death message, and scoreboard
     * to the database.
     * 
     * @param killer
     * @param victim
     * @param message
     * @return
     */
    public boolean saveDeathInfo(DamageSource killer, Player victim, String message) {
        synchronized (this.connection) {
            try {
                final PreparedStatement statement = this.connection.prepareStatement(
                        "INSERT INTO death_log (killer_name, victim_uuid, victim_name, message, victim_new_lives) " +
                                "VALUES (?,?,?,?,?)");


                statement.setString(1, killer.getCausingEntity() instanceof Entity ? killer.getCausingEntity().getName() : killer.getDamageType().getTranslationKey().toString());
                statement.setString(2, victim.getUniqueId().toString());
                statement.setString(3, victim.getName());
                statement.setString(4, message);
                statement.setInt(5, victim.getScoreboard().getObjective("Lives").getScore(victim.getName()).getScore());
                final int rows = statement.executeUpdate();
                statement.close();

                return rows > 0;
            } catch (final SQLException e) {
                e.printStackTrace();
                return false;
            }

        }

    }

    /**
     * Returns a list of deaths from the database about a player
     * 
     * Runs a prepared statement using an input player name to return a list of
     * their deaths. Currently not fully used as the command was left unfinished
     * 
     * @param playerName
     * @param limit
     * @return
     */
    public List<DatabaseMessage> getPlayerDeaths(String playerName, int limit) {

        final List<DatabaseMessage> deaths = new ArrayList<>();

        try {
            String query = "SELECT * FROM death_log WHERE victim_name = ? ORDER BY timestamp DESC";

            if (limit > 0) {
                query += " LIMIT " + limit;
            }

            final PreparedStatement statement = this.connection.prepareStatement(query);
            statement.setString(1, playerName);

            final ResultSet resultSet = statement.executeQuery();

            while (resultSet.next()) {
                deaths.add(DatabaseMessage.fromResultSet(resultSet));
            }

            resultSet.close();
            statement.close();
        } catch (final SQLException e) {
            e.printStackTrace();
        }
        return deaths;
    }


    /**
     * Defines what a database message should contain with getters and setters
     */
    public final static class DatabaseMessage {
        private final int id;
        private final String killerName;
        private final UUID victimUuid;
        private final String victimName;
        private final String message;
        private final int victimNewLives;
        private final Timestamp timestamp;

        public DatabaseMessage(int id, String killerName, UUID victimUuid, String victimName, String message, int victimNewLives, Timestamp timestamp) {
            this.id = id;
            this.killerName = killerName;
            this.victimUuid = victimUuid;
            this.victimName = victimName;
            this.message = message;
            this.victimNewLives = victimNewLives;
            this.timestamp = timestamp;
        }

        public int getId() {
            return id;
        }

        public String getKillerName() {
            return killerName;
        }

        public UUID getVictimUuid() {
            return victimUuid;
        }

        public String getVictimName() {
            return victimName;
        }

        public String getMessage() {
            return message;
        }

        public int getVictimNewLives() {
            return victimNewLives;
        }

        public Timestamp getTimestamp() {
            return timestamp;
        }

        public static DatabaseMessage fromResultSet(ResultSet resultSet) throws SQLException {
            return new DatabaseMessage(
                    resultSet.getInt("id"),
                    resultSet.getString("killer_name"),
                    UUID.fromString(resultSet.getString("victim_uuid")),
                    resultSet.getString("victim_name"),
                    resultSet.getString("message"),
                    resultSet.getInt("victim_new_lives"),
                    resultSet.getTimestamp("timestamp")
            );
        }
    }

    public enum DatabaseType {
        H2
    }

    public static Database getInstance() {
        return instance;
    }
}
